### ISSUE TITLE
Geofence doesn't work when the app terminated.

### ISSUE THREAD

**Issue by tigermobiledev** [Dev-hwang/poly_geofence_service#5]
@Dev-hwang, Thanks for your great package.
I found an issue in this package.
Geofencing works well when the app is in the foreground or background.
However, it does not work when the app is completely terminated.
It seems that this package does not support that feature when the app is terminated.
I think geofencing should work even when the app is off.
Thanks.

**Comment by Dev-hwang** [comment]
@tigermobiledev

Yes. This plugin cannot yet perform geofencing while the app is closed. As introduced in the readme, geofencing can only be done while the app is alive.

Currently this plugin includes the `flutter_foreground_task` plugin. The `flutter_foreground_task` plugin provides foreground services on the Android platform. Here you can use the `WithForegroundTask` widget instead of the `WillStartForegroundTask` widget to do geofencing in the background. Check out this [page](https://pub.dev/packages/flutter_foreground_task) for more details.

However, there is a problem that it does not work properly on iOS. So if you want complete background geofencing on all platforms, i recommend using another plugin.
